### ISSUE TITLE
gmktool x86

### ISSUE THREAD

**Issue by HeartHeroDE** [AlexWaveDiver/TranslaTale#1]
When translating on a mobile device I discovered that the gmktool for TranslaTale is a x64 build. I would suggest using a x86 build for it. I built one myself and uploaded it: https://goo.gl/DDMDvs

**Comment by AlexWaveDiver** [comment]
Oh, I thought the version 0.7 already had a x86 version of GMKTool! Let me check it out

**Comment by AlexWaveDiver** [comment]
Yup! The 0.7 already had a 32bit version of GMKtool. 

 ![32bit](http://i.imgur.com/aVzzJIV.jpg)
