### ISSUE TITLE
Repacking wizard install font problem

### ISSUE THREAD

**Issue by purion** [AlexWaveDiver/TranslaTale#16]
I download all font and install, but TranslaTale not recognize DotumChe font.
I try and try... but program still not recognize DotumChe font... [I use window7(korean language pack)]
font problem is common? or just my computer problem? i wait your answer...
![01](https://cloud.githubusercontent.com/assets/17446052/13277083/4c672ae2-db09-11e5-8313-5af5b76d918d.PNG)

**Comment by Epic3lite-zz** [comment]
DotumChe has an english font name and a korean font name. If you can, try setting your windows language to english, as TranslaTale may be picking up the korean font name and not seeing DotumChe. If you can't set your windows language to english download [virtualbox](https://www.virtualbox.org/) and (~~illegally download~~) get an english windows iso from somewhere.

**Comment by Epic3lite-zz** [comment]
unless @AlexWaveDiver fixes that first :)

**Comment by purion** [comment]
I solve problem. Change windows language(Korean -> English). Thanks your answer!
