### ISSUE TITLE
Missing GMKTool

### ISSUE THREAD

**Issue by rma1994** [AlexWaveDiver/TranslaTale#2]
Hello Alex!
First of all, what a piece of heaven you build! Thanks a bunch for such a great software man! :dart: 

I just found something when I clone your code (in order to change the fonts, since I'll add the portuguese acents é à ç...).
When I do the clone and try to build, it show an error message saying that the GMKTool is missing on path "\TranslaTale\TranslaTale\bin\Debug".
I could fix that by just paste the GMKTool on this path.

So, the github version is missing this guy.

Again, thank you for this great program!

**Comment by AlexWaveDiver** [comment]
On it!

**Comment by AlexWaveDiver** [comment]
Oh, I guess I'd postpone the new update until a new GMKTool version is released :/

**Comment by rma1994** [comment]
That's a good options.
I sent Mika an issue report for this, so we only can hope that she can fix this.
Rust is quite a peculiar language.

**Comment by AlexWaveDiver** [comment]
GMKTool removed, in favor of fjay69's UndertaleTools.
