### ISSUE TITLE
Flowey Dialogue won't advance

### ISSUE THREAD

**Issue by Epic3lite-zz** [AlexWaveDiver/TranslaTale#20]
Repacking my translated strings for flowey dialogue works, but his dialogue is stuck on the first line (the "See that heart, that is your SOUL..." line)

**Comment by AlexWaveDiver** [comment]
Can you put here the line, please?

**Comment by Epic3lite-zz** [comment]
![](http://puu.sh/nzsWN/4c211a2b22.png)

![](http://puu.sh/nzsYv/7124805efe.png)

**Comment by AlexWaveDiver** [comment]
You forgot the "/" at the end

**Comment by Epic3lite-zz** [comment]
oh thanks!
