### ISSUE TITLE
Can't seem to run program

### ISSUE THREAD

**Issue by JRHB314** [AlexWaveDiver/TranslaTale#21]
Downloaded the updated version, but can't seem to figure out how to run it. Might just be being an idiot, but I'm not seeing an exe file. There is something called "Translatale.exe" in the Debug folder but it is actually a XML Config file. Am I supposed to run through Visual Basic directly?--I have only done very basic programs with Visual Basic so not 100% familiar with it. Tried debugging, building, or just "starting" various files, but all throw up errors, specifically that bin\Debug\TranslaTale.exe is missing.

**Comment by AlexWaveDiver** [comment]
You've downloaded the source code instead of the executable

Here you have: https://github.com/AlexWaveDiver/TranslaTale/releases/tag/0.8
