### ISSUE TITLE
TranslaTale does not respond when trying to load data.win

### ISSUE THREAD

**Issue by ghost** [AlexWaveDiver/TranslaTale#22]
:-1:  Help.

**Comment by AlexWaveDiver** [comment]
That's because you must open a strings file, not a winfile.

[Use the tools menu](https://github.com/AlexWaveDiver/TranslaTale/wiki/Unofficial-Tutorial) to extract the strings from your winfile.

**Comment by ghost** [comment]
Ah, ok, thank you!
