### ISSUE TITLE
Norton keeps deleting it

### ISSUE THREAD

**Issue by ghost** [AlexWaveDiver/TranslaTale#31]
Norton keeps deleting it. Please fix!
![why](https://cloud.githubusercontent.com/assets/23317696/24376131/cb400ac2-1308-11e7-9a90-532e6f02ea43.GIF)

**Comment by AlexWaveDiver** [comment]
I can't fix it. It's up to Symantec.

I sent them a good bunch of false positive reports, but alas to no avail. They keep ignoring them.

**Comment by ghost** [comment]
#31 I just submitted another False Positive report.

**Comment by ghost** [comment]
IT WORKS!!!!
