### ISSUE TITLE
Custom font support

### ISSUE THREAD

**Issue by fjay69** [AlexWaveDiver/TranslaTale#4]
Hello! Need support for custom fonts imported from GM:S project, so you can see text preview for any language. Here's simple example, how it could work (on JavaScript, but probably you can to port it): http://rghost.ru/8yzH9l5Nb

**Comment by AlexWaveDiver** [comment]
Ok, added to the next version features list.

I'd love to integrate your UndertaleTools into TranslaTale. Can I? (giving you proper credits and such!) :D

**Comment by fjay69** [comment]
Yes, you can use them. Report if something goes wrong.

**Comment by AlexWaveDiver** [comment]
Of course! I've fixed a couple of bugs already. I'll send you a pull request as soon as I arrive home (I'm at work at this moment)

Thank you, fjay69!

EDIT: Oh, I forgot to ask but under what license is your software?

**Comment by fjay69** [comment]
GPL, but who care?

**Comment by BSoD38** [comment]
Hi, I just wanted to ask... Do you have any ETA concerning the new version of TranslaTale ? We've been on hold since the new update. My team's eagerly waiting for this update !
Thanks for reading, best regards from the french translation team.

**Comment by fjay69** [comment]
You can still use TranslaTale for editing strings, but for unpacking/packing resources you can use my utils.

**Comment by BSoD38** [comment]
So, the strings file that is extracted by your tool is compatible and readable by TranslaTale ? Cool !

**Comment by SL-RU** [comment]
hOi!!1

I'm developed alternative application with some new features, as support for custom fonts and plain text preview mode and with comfortable editing.

You can check out it here: https://github.com/SL-RU/UnderTranslator

**Comment by AlexWaveDiver** [comment]
Just wondering why you're making a TranslaTale clone from scratch instead of collaborating with TT :/ (don't get me wrong, your tool is pretty good!) but I think we can achieve a better toolkit if we all work together on it.

**Comment by SL-RU** [comment]
I don't like VB, heh

And with quick look at your project give me understand, that it is too hard to implement some features here, especially with Windows forms. So I thought it's easier to write it from scratch =/

**Comment by AlexWaveDiver** [comment]
Feature added to v0.8!
