### ISSUE TITLE
repacking

### ISSUE THREAD

**Issue by ghost** [AlexWaveDiver/TranslaTale#6]
Exuse my ignorance (I'm new with this tool).
When I try to repack my modified text I encounter this problem. Here it is: (Yeah, I know. It was in italian but I translated it)
Could you help me out whit this?

*************\* Text of the exception **************
System.IO.FileNotFoundException: Impossibile trovare il file 'C:\Users******_\AppData\Local\Temp\0i2fnixm.qbv\UTFONTS\FONT\UT_8bit.font.gmx'.
Nome file: 'C:\Users\**_******\AppData\Local\Temp\0i2fnixm.qbv\UTFONTS\FONT\UT_8bit.font.gmx'
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   in System.IO.File.Copy(String sourceFileName, String destFileName)
   in TranslaTale.frmFontImporter.repackFonts(String winFile)
   in TranslaTale.frmFontImporter.btnNext_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Assembly loaded **************
mscorlib
    Version assembly: 4.0.0.0
    Version Win32: 4.6.1063.1 built by: NETFXREL3STAGE
##     Code base: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

TranslaTale
    Assembly version: 0.8.0.0
    Version Win32: 0.8.0.0
##     Code base: file:///C:/Users/****/Desktop/Project%20Translation/TranslaTale.v0.8/TranslaTale.exe

Microsoft.VisualBasic
    Versione assembly: 10.0.0.0
    Versione Win32: 14.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1068.2 built by: NETFXREL3STAGE
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Runtime.Remoting
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

UTSpriteFontBox
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
##     Base di codice: file:///C:/Users/**********/Desktop/Project%20Translation/TranslaTale.v0.8/UTSpriteFontBox.DLL

System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1064.2 built by: NETFXREL3STAGE
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.ServiceModel.Web
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Web/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll

System.Runtime.Serialization
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

SMDiagnostics
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll

System.ServiceModel.Internals
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll

System.RunTime.Serialization.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Runtime.Serialization.resources.dll

mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
##     Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll

System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2

**Comment by AlexWaveDiver** [comment]
Have you renamed the font or replaced it on the GM:S project?

**Comment by ghost** [comment]
Yes, now the problem is the same but it indicates another folder and not 0i2fnixm.qbv anymore.

**Comment by AlexWaveDiver** [comment]
Can you attach here your UTfonts GM:S project? Thanks!

**Comment by AlexWaveDiver** [comment]
Closed due to inactivity
